# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LastFMAPITest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LastFMAPITest
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.5'
  pod 'AlamofireNetworkActivityLogger'
  pod 'CocoaLumberjack/Swift'
  pod 'EmptyDataSet-Swift', '~> 4.2.0'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SVProgressHUD'
  pod 'Swinject'
  pod 'TwitterKit'

  target 'LastFMAPITestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LastFMAPITestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
